# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages
latex: false
pandoc: false

matrix:
  include:
    - os: linux
      r: oldrel
    - os: linux
      r: release
    - os: linux
      r: devel
    - os: osx
      r: 3.3
      brew_packages: libgit2

repos:
  docker: https://r.docker.stat.auckland.ac.nz

addons:
  apt:
    packages:
      - libnlopt-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo chown -R $(whoami) /usr/local/share; fi
